CREATE_USER = "insert into entities.users (username, password, first_name, last_name) values (%s) returning id"
CREATE_EVENT_TYPE = "insert into entities.event_types (name, color, description) values (%s) returning name"
CREATE_EVENT = "insert into entities.events (title, start_time, end_time, description, user_id) values (%s) returning title"
GET_ALL_USERS = "select username, first_name, last_name from entities.users"
GET_EVENTS = "select title, start_time, end_time, description event_type_id from events where user_id = (%d)"
GET_ALL_EVENTS_TYPES = "select name, color,description from entities.event_types"
UPDATE_USER = ""
UPDATE_EVENT = ""
UPDATE_EVENT_TYPE = ""